#!/bin/sh
               # export ARCH=arm 
               # export CROSS_COMPILE=arm-linux-gnueabi-
               # make vexpress_ca9x4_defconfig
               # make

                qemu-system-arm \
                    -M vexpress-a9 \
                    -nographic \
                    -m 512M \
                    -kernel u-boot-2017.01/u-boot
